#appium server
appium.url=http://localhost:4723

# device
device.name=Android Emulator
platform.version=11.0

# App
app.package=com.example.todo
app.activity=.MainActivity
app.path=src/test/resources/app/todo.apk

# Timeouts
implicit.wait=10
explicit.wait=15